# Generated by Django 5.0.1 on 2026-02-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_llm_provider_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="default_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
