# Generated by Django 5.0.1 on 2026-02-07 12:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("lyrics", models.TextField()),
                ("description", models.TextField(blank=True)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("pop", "Pop"),
                            ("rock", "Rock"),
                            ("jazz", "Jazz"),
                            ("classical", "Classical"),
                            ("electronic", "Electronic"),
                            ("hiphop", "Hip Hop"),
                            ("country", "Country"),
                            ("rnb", "R&B"),
                            ("blues", "Blues"),
                            ("metal", "Metal"),
                            ("folk", "Folk"),
                            ("ambient", "Ambient"),
                            ("other", "Other"),
                        ],
                        default="pop",
                        max_length=50,
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("energetic", "Energetic"),
                            ("calm", "Calm"),
                            ("romantic", "Romantic"),
                            ("melancholic", "Melancholic"),
                            ("aggressive", "Aggressive"),
                            ("mysterious", "Mysterious"),
                            ("uplifting", "Uplifting"),
                            ("dark", "Dark"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="songs/"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("play_count", models.IntegerField(default=0)),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "songs",
                    models.ManyToManyField(
                        blank=True, related_name="playlists", to="songs.song"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("up", "Upvote"), ("down", "Downvote")], max_length=4
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_votes",
                        to="songs.song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["-created_at"], name="songs_song_created_115a65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["user", "-created_at"], name="songs_song_user_id_e57724_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["is_public", "-upvotes"], name="songs_song_is_publ_a98c94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["genre"], name="songs_song_genre_e809f6_idx"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["song", "vote_type"], name="songs_vote_song_id_7959d4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("user", "song")},
        ),
    ]
