# Generated by Django 5.0.1 on 2026-02-07 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_alter_song_lyrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="duration",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
    ]
